In [1]:
import pandas as pd
import os
from dotenv import load_dotenv
from openai import OpenAI
import json
load_dotenv(override=True)


# ==========================
# OpenAI Configuration
# ==========================

config_str = os.getenv("GPT_LUNA_CONFIG")

if config_str is None:
    raise ValueError("model environment variable is missing")

config = json.loads(config_str)

MODEL_NAME = config["name"]
REASONING_EFFORT = config["reasoning_effort"]

print(f"Using model: {MODEL_NAME} with reasoning effort: {REASONING_EFFORT}")

OPENAI_API_KEY = os.getenv(
    "OPENAI_API_KEY"
)

SLEEP_BETWEEN_CALLS = int(
    os.getenv("SLEEP_BETWEEN_CALLS", "1")
)


client = OpenAI(
    api_key=OPENAI_API_KEY
)

DATA_PATH = os.getenv("DATA_PATH", "../data/")

df=pd.read_csv(f'{DATA_PATH}df_n3.csv')

Using model: gpt-5.6-luna with reasoning effort: low

In [3]:
import json
import random
from collections import defaultdict, Counter

import pandas as pd


# ============================================================
# CONFIGURATION
# ============================================================

# Your original dataframe
# Example:
# df = pd.read_pickle("my_original_df.pkl")
#
# If df is already loaded in your notebook, you don't need
# to change anything here.

BATCH_RESULTS_PATH = "dedup_batch_results_50.jsonl"

N_CONSISTENCY_RUNS = 3


# ============================================================
# 1. LOAD BATCH RESULTS
# ============================================================

def load_batch_results(jsonl_path):
    """
    Load OpenAI batch results from a JSONL file.

    Returns:
        list of raw batch result objects
    """

    results = []

    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if not line:
                continue

            results.append(json.loads(line))

    print(f"[BATCH] Loaded {len(results)} batch results")

    return results


# ============================================================
# 2. EXTRACT LLM RESPONSE FROM BATCH RESULT
# ============================================================

def extract_batch_response(batch_result):
    """
    Extract the text returned by the LLM from a batch result.

    Expected OpenAI Batch structure:

    {
        "custom_id": "...",
        "response": {
            "status_code": 200,
            "body": {
                "choices": [
                    {
                        "message": {
                            "content": "..."
                        }
                    }
                ]
            }
        }
    }
    """

    try:
        response = batch_result["response"]

        body = response["body"]

        choices = body["choices"]

        if not choices:
            return None

        return choices[0]["message"]["content"]

    except Exception as e:
        print(f"[WARN] Could not extract response: {e}")
        return None


# ============================================================
# 3. GET CUSTOM ID
# ============================================================

def get_custom_id(batch_result):
    """
    Return the custom_id used when creating the batch request.

    Change this function ONLY if your batch custom_id has a
    particular structure.
    """

    return batch_result.get("custom_id")


# ============================================================
# 4. PARSE + VALIDATE LLM OUTPUT
# ============================================================

def parse_dedup_output(text, valid_ids):
    """
    Same logic as the original implementation.

    - Removes hallucinated IDs
    - Removes duplicated IDs
    - Adds forgotten IDs as singleton groups
    - Removes synthesis_comment from singleton groups
    """

    if text is None:
        return None

    # Sometimes models return ```json ... ```
    # even though JSON only was requested.
    text = text.strip()

    if text.startswith("```"):
        text = text.replace("```json", "", 1)
        text = text.replace("```", "")
        text = text.strip()

    try:
        data = json.loads(text)
        raw_groups = data.get("groups", [])

    except Exception:
        return None

    valid_ids = set(valid_ids)

    seen = set()
    groups = []

    for g in raw_groups:

        ids = g.get("comment_ids", [])

        clean_ids = [
            i
            for i in ids
            if i in valid_ids and i not in seen
        ]

        if not clean_ids:
            continue

        seen.update(clean_ids)

        synthesis = (
            g.get("synthesis_comment")
            if len(clean_ids) > 1
            else None
        )

        if isinstance(synthesis, str):
            synthesis = synthesis.strip() or None

        groups.append(
            {
                "comment_ids": clean_ids,
                "synthesis_comment": synthesis,
            }
        )

    # Add comments that the LLM forgot
    missing = valid_ids - seen

    for m in missing:
        groups.append(
            {
                "comment_ids": [m],
                "synthesis_comment": None,
            }
        )

    return groups


# ============================================================
# 5. GROUPS -> PAIRS
# ============================================================

def groups_to_pairs(groups):
    """
    Convert groups into pairs of comments that co-occurred
    in the same group.
    """

    pairs = set()

    for g in groups:

        ids = g["comment_ids"]

        for i in range(len(ids)):
            for j in range(i + 1, len(ids)):

                pairs.add(
                    frozenset(
                        (ids[i], ids[j])
                    )
                )

    return pairs


# ============================================================
# 6. UNION-FIND
# ============================================================

class UnionFind:

    def __init__(self, ids):

        self.parent = {
            i: i
            for i in ids
        }

    def find(self, x):

        while self.parent[x] != x:

            self.parent[x] = self.parent[
                self.parent[x]
            ]

            x = self.parent[x]

        return x

    def union(self, a, b):

        ra = self.find(a)
        rb = self.find(b)

        if ra != rb:
            self.parent[ra] = rb


# ============================================================
# 7. SELECT SYNTHESIS COMMENT
# ============================================================

def select_synthesis_for_cluster(
    cluster_ids,
    all_run_groups
):

    target = set(cluster_ids)

    best_group = None
    best_score = -1.0

    for g in all_run_groups:

        if not g.get("synthesis_comment"):
            continue

        gid_set = set(
            g["comment_ids"]
        )

        # Exact match = best possible
        if gid_set == target:

            return g["synthesis_comment"]

        intersection = len(
            gid_set & target
        )

        if intersection == 0:
            continue

        union_size = len(
            gid_set | target
        )

        jaccard = (
            intersection / union_size
        )

        if jaccard > best_score:

            best_score = jaccard
            best_group = g

    return (
        best_group["synthesis_comment"]
        if best_group
        else None
    )


# ============================================================
# 8. AGREEMENT SCORES
# ============================================================

def get_cluster_agreement(
    cluster_ids,
    pair_agreements
):

    agreements = []

    for i in range(len(cluster_ids)):

        for j in range(i + 1, len(cluster_ids)):

            pair = frozenset(
                [
                    cluster_ids[i],
                    cluster_ids[j]
                ]
            )

            if pair in pair_agreements:

                agreements.append(
                    pair_agreements[pair][
                        "agreement_ratio"
                    ]
                )

    return agreements


# ============================================================
# 9. BUILD FINAL CLUSTER ROWS
# ============================================================

def build_cluster_rows(
    patch_id,
    clusters,
    rows,
    all_run_groups,
    pair_agreements
):

    lookup = {
        r["comment_id"]: r
        for r in rows
    }

    cluster_rows = []

    for k, ids in enumerate(clusters):

        synthesis = (
            select_synthesis_for_cluster(
                ids,
                all_run_groups
            )
            if len(ids) > 1
            else None
        )

        cluster_rows.append(
            {
                "patch_id": patch_id,

                "num_comments": len(ids),

                "cluster_id":
                    f"{patch_id}_c{k}",

                "comment_ids": ids,

                "comments": [
                    lookup[i]["generated_comment"]
                    for i in ids
                ],

                "generation_systems": [
                    lookup[i]["generation_system"]
                    for i in ids
                ],

                "categories": [
                    lookup[i]["category"]
                    for i in ids
                ],

                "severities": [
                    lookup[i]["severity"]
                    for i in ids
                ],

                "synthesis_comment":
                    synthesis,

                "agreement_scores":
                    get_cluster_agreement(
                        ids,
                        pair_agreements
                    ),
            }
        )

    return cluster_rows


# ============================================================
# 10. PROCESS ONE PATCH FROM BATCH RESULTS
# ============================================================

def process_patch_from_batch(
    patch_id,
    rows,
    run_outputs
):
    """
    Reproduces the post-LLM processing of the original
    run_dedup_for_patch(), but WITHOUT making any API call.

    run_outputs must contain one LLM response per
    consistency run.
    """

    valid_ids = [
        r["comment_id"]
        for r in rows
    ]

    # --------------------------------------------------------
    # Singleton patch
    # --------------------------------------------------------

    if len(rows) <= 1:

        clusters = [
            [r["comment_id"]]
            for r in rows
        ]

        return build_cluster_rows(
            patch_id,
            clusters,
            rows,
            all_run_groups=[],
            pair_agreements={}
        )

    # --------------------------------------------------------
    # Process the 3 already-generated LLM outputs
    # --------------------------------------------------------

    run_pair_sets = []

    all_run_groups = []

    for run_idx, raw_text in enumerate(run_outputs):

        groups = parse_dedup_output(
            raw_text,
            valid_ids
        )

        if groups is None:

            print(
                f"[WARN] patch {patch_id} "
                f"run {run_idx}: "
                f"unparseable output"
            )

            groups = [
                {
                    "comment_ids": [i],
                    "synthesis_comment": None
                }
                for i in valid_ids
            ]

        run_pair_sets.append(
            groups_to_pairs(groups)
        )

        all_run_groups.extend(groups)

    # --------------------------------------------------------
    # Majority agreement
    # --------------------------------------------------------

    min_votes = (
        len(run_pair_sets) // 2 + 1
    )

    pair_counts = Counter()

    for pairs in run_pair_sets:

        for pair in pairs:

            pair_counts[pair] += 1

    pair_agreements = {

        pair: {
            "agreement_count": count,
            "agreement_ratio":
                count / len(run_pair_sets)
        }

        for pair, count
        in pair_counts.items()
    }

    # --------------------------------------------------------
    # Keep majority-agreed pairs
    # --------------------------------------------------------

    consistent_pairs = {

        pair

        for pair, info
        in pair_agreements.items()

        if info["agreement_count"]
        >= min_votes
    }

    # --------------------------------------------------------
    # Union-Find
    # --------------------------------------------------------

    uf = UnionFind(valid_ids)

    for pair in consistent_pairs:

        a, b = tuple(pair)

        uf.union(a, b)

    # --------------------------------------------------------
    # Build clusters
    # --------------------------------------------------------

    clusters_map = defaultdict(list)

    for comment_id in valid_ids:

        clusters_map[
            uf.find(comment_id)
        ].append(comment_id)

    clusters = list(
        clusters_map.values()
    )

    # --------------------------------------------------------
    # Final cluster rows
    # --------------------------------------------------------

    return build_cluster_rows(
        patch_id,
        clusters,
        rows,
        all_run_groups,
        pair_agreements
    )


# ============================================================
# 11. MAP BATCH RESULTS TO PATCHES / RUNS
# ============================================================

def build_batch_output_map(batch_results):
    """
    Converts the JSONL batch results into:

        {
            custom_id: llm_output
        }

    """

    output_map = {}

    for result in batch_results:

        custom_id = get_custom_id(
            result
        )

        if custom_id is None:
            print(
                "[WARN] Batch result has no custom_id"
            )
            continue

        output_map[
            custom_id
        ] = extract_batch_response(
            result
        )

    return output_map


# ============================================================
# 12. CUSTOM_ID -> PATCH + RUN
# ============================================================


# ============================================================
# 13. MAIN PIPELINE
# ============================================================
def run_batch_dedup_pipeline(
    df,
    batch_results_path
):
    """
    Post-process already completed batch results.

    The JSONL is assumed to be ordered as:

        patch 1 -> run 0
        patch 1 -> run 1
        patch 1 -> run 2

        patch 2 -> run 0
        patch 2 -> run 1
        patch 2 -> run 2

        ...

    No LLM/API calls are made here.
    """

    required_cols = [
        "comment_id",
        "generated_comment",
        "category",
        "generation_system",
        "patch_id",
        "severity",
        "hunk"
    ]

    for c in required_cols:

        if c not in df.columns:

            raise ValueError(
                f"Missing required column: {c}"
            )

    # --------------------------------------------------------
    # Load batch results
    # --------------------------------------------------------

    batch_results = load_batch_results(
        batch_results_path
    )

    batch_outputs = [
        extract_batch_response(result)
        for result in batch_results
    ]

    print(
        f"[BATCH] Loaded {len(batch_outputs)} outputs"
    )

    # --------------------------------------------------------
    # Group dataframe by patch
    # --------------------------------------------------------

    patch_groups = list(
        df.groupby("patch_id")
    )

    total_patches = len(patch_groups)

    expected_outputs = (
        total_patches *
        N_CONSISTENCY_RUNS
    )

    print(
        f"[INFO] Number of patches: "
        f"{total_patches}"
    )

    print(
        f"[INFO] Expected batch outputs: "
        f"{expected_outputs}"
    )

    print(
        f"[INFO] Actual batch outputs: "
        f"{len(batch_outputs)}"
    )

    if len(batch_outputs) != expected_outputs:

        raise ValueError(
            f"Number of batch results does not match "
            f"the expected number.\n"
            f"Expected: {expected_outputs} "
            f"({total_patches} patches × "
            f"{N_CONSISTENCY_RUNS} runs)\n"
            f"Found: {len(batch_outputs)}"
        )

    # --------------------------------------------------------
    # Process patches
    # --------------------------------------------------------

    results = []

    for patch_idx, (patch_id, group) in enumerate(
        patch_groups
    ):

        print(
            f"\n[PATCH {patch_idx + 1}/"
            f"{total_patches}] "
            f"{patch_id} "
            f"({len(group)} comments)"
        )

        rows = group.to_dict(
            "records"
        )

        for r in rows:

            r.setdefault(
                "generated_context",
                ""
            )

        # ----------------------------------------------------
        # Extract the 3 outputs corresponding to this patch
        # ----------------------------------------------------

        start_idx = (
            patch_idx *
            N_CONSISTENCY_RUNS
        )

        end_idx = (
            start_idx +
            N_CONSISTENCY_RUNS
        )

        run_outputs = batch_outputs[
            start_idx:end_idx
        ]

        print(
            f"  Using batch outputs "
            f"{start_idx} → {end_idx - 1}"
        )

        # ----------------------------------------------------
        # Process without API call
        # ----------------------------------------------------

        try:

            patch_cluster_rows = (
                process_patch_from_batch(
                    patch_id,
                    rows,
                    run_outputs
                )
            )

        except Exception as e:

            print(
                f"[FAIL] patch {patch_id}: {e}"
            )

            patch_cluster_rows = [

                {
                    "patch_id":
                        patch_id,

                    "num_comments":
                        len(rows),

                    "cluster_id":
                        f"{patch_id}_c{k}",

                    "comment_ids":
                        [r["comment_id"]],

                    "comments":
                        [r["generated_comment"]],

                    "generation_systems":
                        [r["generation_system"]],

                    "categories":
                        [r["category"]],

                    "severities":
                        [r["severity"]],

                    "synthesis_comment":
                        None,

                    "error":
                        str(e),
                }

                for k, r in enumerate(rows)
            ]

        results.extend(
            patch_cluster_rows
        )

    # --------------------------------------------------------
    # Final DataFrame
    # --------------------------------------------------------

    final_df = pd.DataFrame(
        results
    )

    print(
        "\n[DONE] Batch post-processing finished"
    )

    print(
        f"[DONE] Final dataframe shape: "
        f"{final_df.shape}"
    )

    return final_df

# ============================================================
# 14. RUN
# ============================================================

# Your original dataframe should already be loaded as `df`.
final_df = run_batch_dedup_pipeline(
    df=df,
    batch_results_path=BATCH_RESULTS_PATH
)

print(final_df.head())

[BATCH] Loaded 150 batch results
[BATCH] Loaded 150 outputs
[INFO] Number of patches: 50
[INFO] Expected batch outputs: 150
[INFO] Actual batch outputs: 150

[PATCH 1/50] P000000 (1 comments)
  Using batch outputs 0 → 2

[PATCH 2/50] P000001 (1 comments)
  Using batch outputs 3 → 5

[PATCH 3/50] P000002 (2 comments)
  Using batch outputs 6 → 8

[PATCH 4/50] P000003 (1 comments)
  Using batch outputs 9 → 11

[PATCH 5/50] P000004 (1 comments)
  Using batch outputs 12 → 14

[PATCH 6/50] P000005 (1 comments)
  Using batch outputs 15 → 17

[PATCH 7/50] P000006 (2 comments)
  Using batch outputs 18 → 20

[PATCH 8/50] P000007 (2 comments)
  Using batch outputs 21 → 23

[PATCH 9/50] P000008 (3 comments)
  Using batch outputs 24 → 26

[PATCH 10/50] P000009 (1 comments)
  Using batch outputs 27 → 29

[PATCH 11/50] P000010 (1 comments)
  Using batch outputs 30 → 32

[PATCH 12/50] P000011 (3 comments)
  Using batch outputs 33 → 35

[PATCH 13/50] P000012 (3 comments)
  Using batch outputs 36 → 38

[PATCH 14/50] P000013 (2 comments)
  Using batch outputs 39 → 41

[PATCH 15/50] P000014 (3 comments)
  Using batch outputs 42 → 44

[PATCH 16/50] P000015 (1 comments)
  Using batch outputs 45 → 47

[PATCH 17/50] P000016 (2 comments)
  Using batch outputs 48 → 50

[PATCH 18/50] P000017 (1 comments)
  Using batch outputs 51 → 53

[PATCH 19/50] P000018 (2 comments)
  Using batch outputs 54 → 56

[PATCH 20/50] P000019 (1 comments)
  Using batch outputs 57 → 59

[PATCH 21/50] P000020 (3 comments)
  Using batch outputs 60 → 62

[PATCH 22/50] P000021 (2 comments)
  Using batch outputs 63 → 65

[PATCH 23/50] P000022 (3 comments)
  Using batch outputs 66 → 68

[PATCH 24/50] P000023 (1 comments)
  Using batch outputs 69 → 71

[PATCH 25/50] P000024 (5 comments)
  Using batch outputs 72 → 74

[PATCH 26/50] P000025 (3 comments)
  Using batch outputs 75 → 77

[PATCH 27/50] P000026 (1 comments)
  Using batch outputs 78 → 80

[PATCH 28/50] P000027 (2 comments)
  Using batch outputs 81 → 83

[PATCH 29/50] P000028 (1 comments)
  Using batch outputs 84 → 86

[PATCH 30/50] P000029 (1 comments)
  Using batch outputs 87 → 89

[PATCH 31/50] P000030 (3 comments)
  Using batch outputs 90 → 92

[PATCH 32/50] P000031 (1 comments)
  Using batch outputs 93 → 95

[PATCH 33/50] P000032 (2 comments)
  Using batch outputs 96 → 98

[PATCH 34/50] P000033 (1 comments)
  Using batch outputs 99 → 101

[PATCH 35/50] P000034 (3 comments)
  Using batch outputs 102 → 104

[PATCH 36/50] P000035 (2 comments)
  Using batch outputs 105 → 107

[PATCH 37/50] P000036 (1 comments)
  Using batch outputs 108 → 110

[PATCH 38/50] P000037 (2 comments)
  Using batch outputs 111 → 113

[PATCH 39/50] P000038 (3 comments)
  Using batch outputs 114 → 116

[PATCH 40/50] P000039 (5 comments)
  Using batch outputs 117 → 119

[PATCH 41/50] P000040 (1 comments)
  Using batch outputs 120 → 122

[PATCH 42/50] P000041 (2 comments)
  Using batch outputs 123 → 125

[PATCH 43/50] P000042 (1 comments)
  Using batch outputs 126 → 128

[PATCH 44/50] P000043 (1 comments)
  Using batch outputs 129 → 131

[PATCH 45/50] P000044 (1 comments)
  Using batch outputs 132 → 134

[PATCH 46/50] P000045 (3 comments)
  Using batch outputs 135 → 137

[PATCH 47/50] P000046 (3 comments)
  Using batch outputs 138 → 140

[PATCH 48/50] P000047 (2 comments)
  Using batch outputs 141 → 143

[PATCH 49/50] P000048 (2 comments)
  Using batch outputs 144 → 146

[PATCH 50/50] P000049 (4 comments)
  Using batch outputs 147 → 149

[DONE] Batch post-processing finished
[DONE] Final dataframe shape: (74, 10)
  patch_id  num_comments  cluster_id  \
0  P000000             1  P000000_c0
1  P000001             1  P000001_c0
2  P000002             2  P000002_c0
3  P000003             1  P000003_c0
4  P000004             1  P000004_c0

                                         comment_ids  \
0             [e582ad72-8d9f-418d-a017-4c605b4a6009]
1             [557c8ad0-c25c-4c31-bdb5-463aa09f6dd2]
2  [d1219982-9fea-45e9-97a0-65aeae62d25c, 7265ac7...
3             [cda853dd-b7df-47e2-a9d3-a2d75a5d3b05]
4             [d35ae336-9da1-4d4f-80ce-f2a73dced7d4]

                                            comments  \
0  [The docstring for the `head` method mentions ...
1  [The `cross_entropy` function call is replaced...
2  [Could we remove the remaining `stylesheet.set...
3  [The docstring for `iter_kubernetes_nodes` men...
4  [The docstring for `naive_dice_loss` mentions ...

                                  generation_systems  \
0                           [gpt-4o-mini-2024-07-18]
1                           [gpt-4o-mini-2024-07-18]
2  [gpt-5.4-mini-2026-03-17, gpt-4o-mini-2024-07-18]
3                           [gpt-4o-mini-2024-07-18]
4                           [gpt-4o-mini-2024-07-18]

                       categories     severities  \
0                 [Documentation]       [Medium]
1                   [Correctness]         [High]
2  [Maintainability, Correctness]  [Low, Medium]
3                 [Documentation]       [Medium]
4                 [Documentation]       [Medium]

                                   synthesis_comment agreement_scores
0                                               None               []
1                                               None               []
2  Now that the line edit's stylesheet is defined...            [1.0]
3                                               None               []
4                                               None               []

In [11]:
final_df.head(50)

,patch_id,num_comments,cluster_id,comment_ids,comments,generation_systems,categories,severities,synthesis_comment,agreement_scores
0,P000000,1,P000000_c0,[e582ad72-8d9f-418d-a017-4c605b4a6009],[The docstring for the `head` method mentions ...,[gpt-4o-mini-2024-07-18],[Documentation],[Medium],None,[]
1,P000001,1,P000001_c0,[557c8ad0-c25c-4c31-bdb5-463aa09f6dd2],[The `cross_entropy` function call is replaced...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
2,P000002,2,P000002_c0,"[d1219982-9fea-45e9-97a0-65aeae62d25c, 7265ac7...",[Could we remove the remaining `stylesheet.set...,"[gpt-5.4-mini-2026-03-17, gpt-4o-mini-2024-07-18]","[Maintainability, Correctness]","[Low, Medium]",Now that the line edit's stylesheet is defined...,[1.0]
3,P000003,1,P000003_c0,[cda853dd-b7df-47e2-a9d3-a2d75a5d3b05],[The docstring for `iter_kubernetes_nodes` men...,[gpt-4o-mini-2024-07-18],[Documentation],[Medium],None,[]
4,P000004,1,P000004_c0,[d35ae336-9da1-4d4f-80ce-f2a73dced7d4],[The docstring for `naive_dice_loss` mentions ...,[gpt-4o-mini-2024-07-18],[Documentation],[Medium],None,[]
5,P000005,1,P000005_c0,[7506dca5-ec7c-4dd0-afd3-59fcf8c4b358],[Is it intentional to remove the deprecation w...,[gpt-4o-mini-2024-07-18],[Correctness],[Medium],None,[]
6,P000006,2,P000006_c0,"[9c09de10-d775-42dc-998c-f75205f8a305, 6f13e3b...",[The method call to `_compact_times()` has bee...,"[gpt-4o-mini-2024-07-18, gpt-5.4-mini-2026-03-17]","[Correctness, Correctness]","[High, Medium]",Removing response-time compaction from recalcu...,[1.0]
7,P000007,1,P000007_c0,[3e75fbd5-661c-48e0-9d7c-918374329169],[The call to `utils.to_native_string` is now p...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
8,P000007,1,P000007_c1,[cf3a5d04-5f50-4454-8d54-ff8fc104374b],[Could this preserve the type of the parsed UR...,[gpt-5.6-luna],[Correctness],[Medium],None,[]
9,P000008,2,P000008_c0,"[864abeeb-9771-46f1-9308-2dd004c8042a, a4f8c28...","[Could this retain the `getattr(cls, ""task_nam...","[gpt-5.6-luna, gpt-5.4-mini-2026-03-17]","[Correctness, Correctness]","[Medium, Medium]",Directly accessing `cls.task_namespace` can ra...,[1.0]
10,P000008,1,P000008_c1,[a5f11bc4-af9c-4eb2-a85e-2e5185c20d47],[The check for `task_namespace` should also in...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
11,P000009,1,P000009_c0,[cfe36a21-32f1-4907-853c-0d5d1c7bc11d],[The formatting changes may improve readabilit...,[gpt-4o-mini-2024-07-18],[Readability],[Medium],None,[]
12,P000010,1,P000010_c0,[42285d29-2009-459d-ba2a-8ecf184379be],"[The change from ""Example:"" to ""Examples"" and ...",[gpt-4o-mini-2024-07-18],[Documentation],[Medium],None,[]
13,P000011,3,P000011_c0,"[70e3cd70-fc17-45ac-ba57-07325366cb6b, bd69090...",[The line `result = deepcopy(result)` was remo...,"[gpt-4o-mini-2024-07-18, gpt-5.6-luna, gpt-5.4...","[Correctness, Correctness, Correctness]","[High, Medium, Medium]",Removing the deepcopy causes result[DATA] to b...,"[1.0, 1.0, 1.0]"
14,P000012,3,P000012_c0,"[d2afe792-e407-4cd7-bacc-5200f6a24e4d, b4aa4e4...",[The line `if not build_manager.setup_build(re...,"[gpt-4o-mini-2024-07-18, gpt-5.6-luna, gpt-5.4...","[Correctness, Correctness, Correctness]","[High, Medium, Medium]",Please retain the BUILD_DIR validation after s...,"[1.0, 1.0, 1.0]"
15,P000013,1,P000013_c0,[dd36d5f9-65b5-4fbc-8480-c7e4b5c3c82a],[`UTXOList.insert_utxo()` no longer stores the...,[gpt-5.4-mini-2026-03-17],[Correctness],[Medium],None,[]
16,P000013,1,P000013_c1,[1e97d5f2-b896-4131-875e-36212bdf6029],[The comment about storing the full outpoint h...,[gpt-4o-mini-2024-07-18],[Maintainability],[Medium],None,[]
17,P000014,1,P000014_c0,[1e1ba03e-8bd9-4c78-9b92-7a5a10e7a4df],"[[Correctness] In `generate_new_function`, the...",[gpt-5.4-mini-2026-03-17],[Correctness],[High],None,[]
18,P000014,1,P000014_c1,[d485b786-f420-467e-9b6c-566025979d64],[The comment preceding the original method has...,[gpt-4o-mini-2024-07-18],[Documentation],[Medium],None,[]
19,P000014,1,P000014_c2,[bf8ead64-8935-462c-b709-6d8d2815d87d],[The method name was changed from `generate_di...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
20,P000015,1,P000015_c0,[96ec5d0a-ec4c-4096-ad8f-2c328396a08a],[The new code introduces an exception logging ...,[gpt-4o-mini-2024-07-18],[Correctness],[Medium],None,[]
21,P000016,1,P000016_c0,[a16ec10e-016d-4384-b97f-8021124f89c9],[The `_is_spmv_supported_node_feat` function w...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
22,P000016,1,P000016_c1,[866b6295-b5df-47a6-a615-e13429fbd994],[[Maintainability] The new `F.ndim(B) > 2` fla...,[gpt-5.4-mini-2026-03-17],[Maintainability],[Low],None,[]
23,P000017,1,P000017_c0,[11607b8b-d1ee-4618-be78-78bbafdf3a8d],[The command options have been changed from `-...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
24,P000018,2,P000018_c0,"[65fdc062-9005-48c9-8397-29318193b137, d613d9e...",[By removing the check for `settings.HEROKU_DE...,"[gpt-4o-mini-2024-07-18, gpt-5.4-mini-2026-03-17]","[Correctness, Correctness]","[High, High]",Removing the `settings.HEROKU_DEMO` branch may...,[1.0]
25,P000019,1,P000019_c0,[9ef3d0cf-9862-4eb1-981a-d65bb3bfaede],[The change from `return 0` to `return 1` in t...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
26,P000020,3,P000020_c0,"[06104b08-c1ee-499d-b1d2-6d18d2804697, 265f681...",[Since this logic appears in both the old and ...,"[gpt-4o-mini-2024-07-18, gpt-4o-mini-2024-07-1...","[Maintainability, Correctness, Correctness]","[Low, Medium, Medium]",Moving `_broadcast_bn_buffer()` below the eval...,"[0.6666666666666666, 0.6666666666666666, 1.0]"
27,P000021,1,P000021_c0,[60d5f556-e3d9-4902-b914-69b48fd719e5],[`prev_result()`/`next_result()` now call `res...,[gpt-5.4-mini-2026-03-17],[Correctness],[High],None,[]
28,P000021,1,P000021_c1,[625aea66-aa42-4e34-a02f-129ae96315c7],[Should the search_match_changed signal be rem...,[gpt-4o-mini-2024-07-18],[Design],[Medium],None,[]
29,P000022,1,P000022_c0,[e8f426cf-3cf2-4e7c-a16a-ee51e7a6c46e],[`read_dropin_dir()` now unconditionally calls...,[gpt-5.4-mini-2026-03-17],[Correctness],[High],None,[]
30,P000022,1,P000022_c1,[b0eff1f9-42ac-4d50-b3f5-13c02e532962],[`read_dropin_dir()` iterates over every entry...,[gpt-5.4-mini-2026-03-17],[Correctness],[Medium],None,[]
31,P000022,1,P000022_c2,[c3cd0e98-3d62-4461-9898-7176b4c37f6c],[The method `read_dropin_dir()` appears to be ...,[gpt-4o-mini-2024-07-18],[Correctness],[Medium],None,[]
32,P000023,1,P000023_c0,[0ba75abf-59a5-4c65-9ff5-c2190495cff3],[The line `source_address = self.server_conn.s...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
33,P000024,1,P000024_c0,[0a1bf0b9-7eab-4e99-8ba2-f0a10769bc3b],[The new `formatted` string uses named placeho...,[gpt-5.4-mini-2026-03-17],[Correctness],[High],None,[]
34,P000024,1,P000024_c1,[c0b7c6c0-8469-4dd8-83e8-347f958a91c2],[`c.fetchone()` is called after the `with self...,[gpt-5.4-mini-2026-03-17],[Correctness],[Medium],None,[]
35,P000024,1,P000024_c2,[c2b50e8b-600b-4057-bc31-78dae842a9ce],[`caught_last_24_hour` now comes from `COUNT(e...,[gpt-5.4-mini-2026-03-17],[Correctness],[Medium],None,[]
36,P000024,2,P000024_c3,"[a92c9171-d723-4888-82b2-4daea55b78ea, b17c086...",[The formatted string in `emit_event` is missi...,"[gpt-4o-mini-2024-07-18, gpt-5.6-luna]","[Correctness, Correctness]","[High, Low]",The formatted message opens a parenthesized se...,[0.6666666666666666]
37,P000025,3,P000025_c0,"[834f1e18-06fd-4fcf-8ff2-618bd99de998, 2de0461...",[The method name was changed from `next_occurr...,"[gpt-4o-mini-2024-07-18, gpt-5.4-mini-2026-03-...","[Correctness, Correctness, Correctness]","[High, Medium, Medium]","The helper was renamed with a misspelling, whi...","[1.0, 1.0, 1.0]"
38,P000026,1,P000026_c0,[a4e1d892-05c8-46cd-b475-016ba639708d],[The change from `iteritems()` to `items()` su...,[gpt-4o-mini-2024-07-18],[Correctness],[Medium],None,[]
39,P000027,2,P000027_c0,"[f18f1300-378b-471d-97e5-8249a78baa29, 462870c...",[The original check for bounding box coordinat...,"[gpt-4o-mini-2024-07-18, gpt-4o-mini-2024-07-18]","[Correctness, Maintainability]","[High, Medium]",Replacing the original coordinate-boundary che...,[0.6666666666666666]
40,P000028,1,P000028_c0,[e032b1ef-3265-4128-ac3a-631f84662c84],[The parameter `incoming_words` was changed to...,[gpt-4o-mini-2024-07-18],[Readability],[Medium],None,[]
41,P000029,1,P000029_c0,[aedc6d87-ac30-4586-8be9-52eb10f3231c],[The change in the check for fork mode (`not u...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
42,P000030,2,P000030_c0,"[a89b4955-6f86-4c32-8dd2-35f385f2dc51, 9a91cad...",[`qute_back()` calls `urllib.parse.unquote(......,"[gpt-5.4-mini-2026-03-17, gpt-5.4-mini-2026-03...","[Correctness, Correctness]","[High, High]","Import urllib.parse explicitly, since both the...",[1.0]
43,P000030,1,P000030_c1,[61aed0a7-4d92-49bb-aa63-cdd7cd06a642],"[The import of `from itertools import chain, d...",[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
44,P000031,1,P000031_c0,[0fb90f53-fb01-412d-94db-67d4cc69456f],[The test function `test_universe_empty_ROMol`...,[gpt-4o-mini-2024-07-18],[Design],[Medium],None,[]
45,P000032,2,P000032_c0,"[6104177f-ddeb-489c-bef7-5e65126d244d, 72042fd...",[Could this use a clearer format such as `Valu...,"[gpt-5.6-luna, gpt-4o-mini-2024-07-18]","[Readability, Readability]","[Low, Medium]",The new `{name:value}` formatting is less clea...,[1.0]
46,P000033,1,P000033_c0,[c5b9495a-29b4-46a3-9101-c01ee92b2ee6],[The changes to the docstring simplify the des...,[gpt-4o-mini-2024-07-18],[Readability],[Medium],None,[]
47,P000034,1,P000034_c0,[86599cda-4556-4631-b46b-a87215719edf],[The handling of window decorations based on t...,[gpt-4o-mini-2024-07-18],[Correctness],[High],None,[]
48,P000034,2,P000034_c1,"[a87ebdb4-d316-4623-a9a5-7cd56ee16d7b, 6513622...",[The setting documentation still says “This se...,"[gpt-5.6-luna, gpt-5.4-mini-2026-03-17]","[Documentation, Documentation]","[Low, Medium]",The setting's description and restart flag sho...,[1.0]
49,P000035,2,P000035_c0,"[f94d2ef8-cd9c-4152-9fcc-35ed2d09d1ae, 1a6d816...",[Did you mean to drop the canonical `id` attri...,"[gpt-5.4-mini-2026-03-17, gpt-4o-mini-2024-07-18]","[Design, Correctness]","[Medium, High]",Replacing `self.id` with `self.planner_id` may...,[1.0]

In [4]:
import pandas as pd

jsonl_path = "dedup_batch_results_50.jsonl"

batch_df = pd.read_json(
    jsonl_path,
    lines=True
)

batch_df.head()

,id,custom_id,response,error
0,batch_req_6a82f2065e50819097c30378e3921406,dedup_P000000_run_0,"{'status_code': 200, 'request_id': '201d5513-c...",NaN
1,batch_req_6a82f2067bf48190b712a6b1b7802c88,dedup_P000000_run_1,"{'status_code': 200, 'request_id': '35f32c1f-f...",NaN
2,batch_req_6a82f2067c54819099993a6146994d08,dedup_P000000_run_2,"{'status_code': 200, 'request_id': '8d18de7d-a...",NaN
3,batch_req_6a82f20676a88190a499b595c5761e0a,dedup_P000001_run_0,"{'status_code': 200, 'request_id': '5703cc9e-0...",NaN
4,batch_req_6a82f20675208190a4586b254fbee522,dedup_P000001_run_1,"{'status_code': 200, 'request_id': '36fab436-0...",NaN

In [ ]:
df = pd.read_csv(f'{DATA_PATH}df_n0.csv')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   old_hunk  100 non-null    object
 1   oldf      100 non-null    object
 2   hunk      100 non-null    object
 3   comment   100 non-null    object
 4   ids       100 non-null    object
 5   repo      100 non-null    object
 6   ghid      100 non-null    int64
 7   old       100 non-null    object
 8   new       100 non-null    object
 9   lang      100 non-null    object
 10  patch_id  100 non-null    object
dtypes: int64(1), object(10)
memory usage: 8.7+ KB

In [8]:
df_comments = pd.read_csv(f'{DATA_PATH}df_n3.csv')

In [10]:
df_comments.head(50)

,comment_id,generated_comment,category,generation_system,patch_id,severity,generation_file,human_comment,hunk,relevant_context,relevant_same_file_code_hunks,relevant_different_files_code_hunks
0,e582ad72-8d9f-418d-a017-4c605b4a6009,The docstring for the `head` method mentions t...,Documentation,gpt-4o-mini-2024-07-18,P000000,Medium,df_n3_3.csv,"Is the name ""head"" a convention for health che...","@@ -274,6 +274,7 @@ class RootPathHandler(Base...",class RootPathHandler(BaseTaskHistoryHandler):...,"[{'filename': 'luigi/server.py', 'patch': '@@ ...","[{'filename': 'test/server_test.py', 'patch': ..."
1,557c8ad0-c25c-4c31-bdb5-463aa09f6dd2,The `cross_entropy` function call is replaced ...,Correctness,gpt-4o-mini-2024-07-18,P000001,High,df_n3_3.csv,"`F.cross_entropy`? Also, isn't `tran_acc` requ...","@@ -117,7 +117,8 @@ def main(args):\n ...",def main(args):\n # split dataset into trai...,[{'filename': 'examples/mxnet/rgcn/entity_clas...,[]
2,d1219982-9fea-45e9-97a0-65aeae62d25c,Could we remove the remaining `stylesheet.set_...,Maintainability,gpt-5.4-mini-2026-03-17,P000002,Low,df_n3_1.csv,Couldn't you move the stylesheet to `ConsoleWi...,"@@ -48,12 +48,6 @@ class ConsoleLineEdit(miscw...",class ConsoleLineEdit(miscwidgets.CommandLineE...,[{'filename': 'qutebrowser/misc/consolewidget....,"[{'filename': 'doc/help/settings.asciidoc', 'p..."
3,7265ac74-5a5c-4090-be08-b00cff51e8f5,The `STYLESHEET` variable has been removed wit...,Correctness,gpt-4o-mini-2024-07-18,P000002,Medium,df_n3_3.csv,Couldn't you move the stylesheet to `ConsoleWi...,"@@ -48,12 +48,6 @@ class ConsoleLineEdit(miscw...",class ConsoleLineEdit(miscwidgets.CommandLineE...,[{'filename': 'qutebrowser/misc/consolewidget....,"[{'filename': 'doc/help/settings.asciidoc', 'p..."
4,cda853dd-b7df-47e2-a9d3-a2d75a5d3b05,The docstring for `iter_kubernetes_nodes` ment...,Documentation,gpt-4o-mini-2024-07-18,P000003,Medium,df_n3_3.csv,please update all the docstring below in other...,"@@ -2229,7 +2229,7 @@ class ApiClientImpl(ApiC...",class ApiClientImpl(ApiClient):\n def iter_...,[{'filename': 'google/cloud/forseti/services/i...,[{'filename': 'google/cloud/forseti/services/i...
5,d35ae336-9da1-4d4f-80ce-f2a73dced7d4,The docstring for `naive_dice_loss` mentions t...,Documentation,gpt-4o-mini-2024-07-18,P000004,Medium,df_n3_3.csv,use_second_power=True -> naive_dice=False,"@@ -51,8 +51,8 @@ def naive_dice_loss(pred,\n ...","def naive_dice_loss(pred,\n ...",[{'filename': 'mmdet/models/losses/dice_loss.p...,[{'filename': 'configs/maskformer/maskformer_r...
6,7506dca5-ec7c-4dd0-afd3-59fcf8c4b358,Is it intentional to remove the deprecation wa...,Correctness,gpt-4o-mini-2024-07-18,P000005,Medium,df_n3_3.csv,```suggestion ``` I can't find the versionchan...,"@@ -903,10 +903,6 @@ class PDBWriter(base.Writ...",class PDBWriter(base.WriterBase):\n def wri...,[],"[{'filename': 'package/CHANGELOG', 'patch': ""@..."
7,9c09de10-d775-42dc-998c-f75205f8a305,The method call to `_compact_times()` has been...,Correctness,gpt-4o-mini-2024-07-18,P000006,High,df_n3_3.csv,We don't need to compact times for each KPIset...,"@@ -167,8 +167,6 @@ class KPISet(BetterDict):\...",class KPISet(BetterDict):\n def __init__(se...,"[{'filename': 'bzt/modules/aggregator.py', 'pa...","[{'filename': 'site/dat/docs/Changelog.md', 'p..."
8,6f13e3b2-29b3-4493-ac9f-96481d60f39a,`recalculate()` no longer compacts `RESP_TIMES...,Correctness,gpt-5.4-mini-2026-03-17,P000006,Medium,df_n3_1.csv,We don't need to compact times for each KPIset...,"@@ -167,8 +167,6 @@ class KPISet(BetterDict):\...",class KPISet(BetterDict):\n def __init__(se...,"[{'filename': 'bzt/modules/aggregator.py', 'pa...","[{'filename': 'site/dat/docs/Changelog.md', 'p..."
9,3e75fbd5-661c-48e0-9d7c-918374329169,The call to `utils.to_native_string` is now pr...,Correctness,gpt-4o-mini-2024-07-18,P000007,High,df_n3_3.csv,A quick dive into the CPython codebase shows t...,"@@ -55,14 +55,8 @@ class MockRequest(object):\...","from .compat import urlparse, urlunparse\nfrom...","[{'filename': 'requests/cookies.py', 'patch': ...","[{'filename': 'requests/_internal_utils.py', '..."
10,cf3a5d04-5f50-4454-8d54-ff8fc104374b,Could this preserve the type of the parsed URL...,Correctness,gpt-5.6-luna,P000007,Medium,df_n3_2.csv,A quick dive into the CPython codebase shows t...,"@@ -55,14 +55,8 @@ class MockRequest(object):\...","from .compat import urlparse, urlunparse\nfrom...","[{'filename': 'requests/cookies.py', 'patch': ...","[{'filename': 'requests/_internal_utils.py', '..."
11,864abeeb-9771-46f1-9308-2dd004c8042a,"Could this retain the `getattr(cls, ""task_name...",Correctness,gpt-5.6-luna,P000008,Medium,df_n3_2.csv,"instead of a `getattr` call here, can you just...","@@ -67,7 +67,7 @@ class Register(abc.ABCMeta):...",class Register(abc.ABCMeta):\n _default_nam...,"[{'filename': 'luigi/task_register.py', 'patch...","[{'filename': 'luigi/task.py', 'patch': '@@ -5..."
12,a4f8c28e-f59e-4f51-9673-517ce24e92a1,Using `cls.task_namespace` here assumes every ...,Correctness,gpt-5.4-mini-2026-03-17,P000008,Medium,df_n3_1.csv,"instead of a `getattr` call here, can you just...","@@ -67,7 +67,7 @@ class Register(abc.ABCMeta):...",class Register(abc.ABCMeta):\n _default_nam...,"[{'filename': 'luigi/task_register.py', 'patch...","[{'filename': 'luigi/task.py', 'patch': '@@ -5..."
13,a5f11bc4-af9c-4eb2-a85e-2e5185c20d47,The check for `task_namespace` should also inc...,Correctness,gpt-4o-mini-2024-07-18,P000008,High,df_n3_3.csv,"instead of a `getattr` call here, can you just...","@@ -67,7 +67,7 @@ class Register(abc.ABCMeta):...",class Register(abc.ABCMeta):\n _default_nam...,"[{'filename': 'luigi/task_register.py', 'patch...","[{'filename': 'luigi/task.py', 'patch': '@@ -5..."
14,cfe36a21-32f1-4907-853c-0d5d1c7bc11d,The formatting changes may improve readability...,Readability,gpt-4o-mini-2024-07-18,P000009,Medium,df_n3_3.csv,I would suggest splitting that long string int...,"@@ -75,10 +75,8 @@ class TestCellosaurus(unitt...",class TestCellosaurus(unittest.TestCase):\n ...,"[{'filename': 'Tests/test_cellosaurus.py', 'pa...",[]
15,42285d29-2009-459d-ba2a-8ecf184379be,"The change from ""Example:"" to ""Examples"" and t...",Documentation,gpt-4o-mini-2024-07-18,P000010,Medium,df_n3_3.csv,Does this render correctly? Do we need somethi...,"@@ -5,7 +5,8 @@\n # package.\n """"""Simple prote...","""""""Simple protein analysis.\n\nExamples\n-----...","[{'filename': 'Bio/SeqUtils/ProtParam.py', 'pa...","[{'filename': 'Bio/motifs/minimal.py', 'patch'..."
16,70e3cd70-fc17-45ac-ba57-07325366cb6b,The line `result = deepcopy(result)` was remov...,Correctness,gpt-4o-mini-2024-07-18,P000011,High,df_n3_3.csv,Why this line is necessary?,"@@ -570,7 +570,6 @@ class Node(PlenumNode, Has...","class Node(PlenumNode, HasPoolManager):\n d...","[{'filename': 'sovrin_node/server/node.py', 'p...",[{'filename': 'sovrin_node/test/replay/test_le...
17,bd69090b-17da-4d49-8742-e20310deaa18,Removing the `deepcopy` makes `result[DATA]` a...,Correctness,gpt-5.6-luna,P000011,Medium,df_n3_2.csv,Why this line is necessary?,"@@ -570,7 +570,6 @@ class Node(PlenumNode, Has...","class Node(PlenumNode, HasPoolManager):\n d...","[{'filename': 'sovrin_node/server/node.py', 'p...",[{'filename': 'sovrin_node/test/replay/test_le...
18,6a6c1bee-b0a7-4349-80ae-59d62ade76f2,Should we keep the `deepcopy` here? `result = ...,Correctness,gpt-5.4-mini-2026-03-17,P000011,Medium,df_n3_1.csv,Why this line is necessary?,"@@ -570,7 +570,6 @@ class Node(PlenumNode, Has...","class Node(PlenumNode, HasPoolManager):\n d...","[{'filename': 'sovrin_node/server/node.py', 'p...",[{'filename': 'sovrin_node/test/replay/test_le...
19,d2afe792-e407-4cd7-bacc-5200f6a24e4d,The line `if not build_manager.setup_build(rev...,Correctness,gpt-4o-mini-2024-07-18,P000012,High,df_n3_3.csv,do we even need to check build_directory ?,"@@ -595,11 +595,10 @@ def do_corpus_pruning(co...","def do_corpus_pruning(context, last_execution_...",[{'filename': 'src/python/bot/tasks/corpus_pru...,[{'filename': 'src/python/tests/core/bot/tasks...
20,b4aa4e48-55e6-422a-a08e-1abf5f337ebb,"By removing the `not build_directory` check, a...",Correctness,gpt-5.6-luna,P000012,Medium,df_n3_2.csv,do we even need to check build_directory ?,"@@ -595,11 +595,10 @@ def do_corpus_pruning(co...","def do_corpus_pruning(context, last_execution_...",[{'filename': 'src/python/bot/tasks/corpus_pru...,[{'filename': 'src/python/tests/core/bot/tasks...
21,9c30ecd9-5cc4-4bff-ac39-c542838e2a1c,`do_corpus_pruning()` no longer checks that `B...,Correctness,gpt-5.4-mini-2026-03-17,P000012,Medium,df_n3_1.csv,do we even need to check build_directory ?,"@@ -595,11 +595,10 @@ def do_corpus_pruning(co...","def do_corpus_pruning(context, last_execution_...",[{'filename': 'src/python/bot/tasks/corpus_pru...,[{'filename': 'src/python/tests/core/bot/tasks...
22,dd36d5f9-65b5-4fbc-8480-c7e4b5c3c82a,`UTXOList.insert_utxo()` no longer stores the ...,Correctness,gpt-5.4-mini-2026-03-17,P000013,Medium,df_n3_1.csv,"There are already a few similar lines below, i...","@@ -96,9 +96,8 @@ class UTXOList(MyTreeView):\...",class UTXOList(MyTreeView):\n class Columns...,"[{'filename': 'electrum/gui/qt/utxo_list.py', ...","[{'filename': 'electrum/gui/qt/util.py', 'patc..."
23,1e97d5f2-b896-4131-875e-36212bdf6029,The comment about storing the full outpoint ha...,Maintainability,gpt-4o-mini-2024-07-18,P000013,Medium,df_n3_3.csv,"There are already a few similar lines below, i...","@@ -96,9 +96,8 @@ class UTXOList(MyTreeView):\...",class UTXOList(MyTreeView):\n class Columns...,"[{'filename': 'electrum/gui/qt/utxo_list.py', ...","[{'filename': 'electrum/gui/qt/util.py', 'patc..."
24,1e1ba03e-8bd9-4c78-9b92-7a5a10e7a4df,"[Correctness] In `generate_new_function`, the ...",Correctness,gpt-5.4-mini-2026-03-17,P000014,High,df_n3_1.csv,"No need for an ""else"" after ""continue"". And: d...","@@ -1974,9 +1974,7 @@ class ModuleNode(Nodes.N...","def generate_dict_getter_function(self, scope,...","[{'filename': 'Cython/Compiler/ModuleNode.py',...","[{'filename': 'Cython/Compiler/Nodes.py', 'pat..."
25,d485b786-f420-467e-9b6c-566025979d64,The comment preceding the original method has ...,Documentation,gpt-4o-mini-2024-07-18,P000014,Medium,df_n3_3.csv,"No need for an ""else"" after ""continue"". And: d...","@@ -1974,9 +1974,7 @@ class ModuleNode(Nodes.N...","def generate_dict_getter_function(self, scope,...","[{'filename': 'Cython/Compiler/ModuleNode.py',...","[{'filename': 'Cython/Compiler/Nodes.py', 'pat..."
26,bf8ead64-8935-462c-b709-6d8d2815d87d,The method name was changed from `generate_dic...,Correctness,gpt-4o-mini-2024-07-18,P000014,High,df_n3_3.csv,"No need for an ""else"" after ""continue"". And: d...","@@ -1974,9 +1974,7 @@ class ModuleNode(Nodes.N...","def generate_dict_getter_function(self, scope,...","[{'filename': 'Cython/Compiler/ModuleNode.py',...","[{'filename': 'Cython/Compiler/Nodes.py', 'pat..."
27,96ec5d0a-ec4c-4096-ad8f-2c328396a08a,The new code introduces an exception logging f...,Correctness,gpt-4o-mini-2024-07-18,P000015,Medium,df_n3_3.csv,Keep this at exception level so that the stack...,"@@ -169,7 +169,7 @@ class InventorySummary(obj...",from google.cloud.forseti.common.util import e...,[{'filename': 'google/cloud/forseti/notifier/n...,[{'filename': 'google/cloud/forseti/common/uti...
28,a16ec10e-016d-4384-b97f-8021124f89c9,The `_is_spmv_supported_node_feat` function wa...,Correctness,gpt-4o-mini-2024-07-18,P000016,High,df_n3_3.csv,"Since it's always returning True, we can remov...","@@ -32,10 +32,6 @@ class MessageFunction(Built...",class MessageFunction(BuiltinFunction):\n d...,[{'filename': 'python/dgl/function/message.py'...,[{'filename': 'python/dgl/runtime/ir/executor....
29,866b6295-b5df-47a6-a615-e13429fbd994,[Maintainability] The new `F.ndim(B) > 2` flat...,Maintainability,gpt-5.4-mini-2026-03-17,P000016,Low,df_n3_1.csv,"Since it's always returning True, we can remov...","@@ -32,10 +32,6 @@ class MessageFunction(Built...",class MessageFunction(BuiltinFunction):\n d...,[{'filename': 'python/dgl/function/message.py'...,[{'filename': 'python/dgl/runtime/ir/executor....
30,11607b8b-d1ee-4618-be78-78bbafdf3a8d,The command options have been changed from `-f...,Correctness,gpt-4o-mini-2024-07-18,P000017,High,df_n3_3.csv,need to add check to make sure that crash.inpu...,"@@ -96,9 +96,9 @@ class IntegrationTest(unitte...",import os\nimport unittest\n\nfrom bot.fuzzers...,[{'filename': 'src/python/tests/core/bot/fuzze...,[{'filename': 'src/python/bot/fuzzers/honggfuz...
31,65fdc062-9005-48c9-8397-29318193b137,By removing the check for `settings.HEROKU_DEM...,Correctness,gpt-4o-mini-2024-07-18,P000018,High,df_n3_3.csv,We don't need `or settings.HEROKU_DEMO` here o...,"@@ -14,7 +14,7 @@ from django.contrib.auth.vie...",from django.conf import settings\nfrom django....,"[{'filename': 'pontoon/allauth_urls.py', 'patc...","[{'filename': 'docs/admin/deployment.rst', 'pa..."
32,d613d9e3-c77e-4765-ad01-dff3b13558d2,Removing the `HEROKU_DEMO` fallback here means...,Correctness,gpt-5.4-mini-2026-03-17,P000018,High,df_n3_1.csv,We don't need `or settings.HEROKU_DEMO` here o...,"@@ -14,7 +14,7 @@ from django.contrib.auth.vie...",from django.conf import settings\nfrom django....,"[{'filename': 'pontoon/allauth_urls.py', 'patc...","[{'filename': 'docs/admin/deployment.rst', 'pa..."
33,9ef3d0cf-9862-4eb1-981a-d65bb3bfaede,The change from `return 0` to `return 1` in th...,Correctness,gpt-4o-mini-2024-07-18,P000019,High,df_n3_3.csv,I suppose that 1 would be better here. Please ...,"@@ -170,7 +170,7 @@ def main(args):\n ...",import dnf.exceptions\n\ndef main(args):\n ...,"[{'filename': 'dnf/base.py', 'patch': '@@ -235...","[{'filename': 'dnf/conf/config.py', 'patch': ""..."
34,06104b08-c1ee-499d-b1d2-6d18d2804697,Since this logic appears in both the old and n...,Maintainability,gpt-4o-mini-2024-07-18,P000020,Low,df_n3_3.csv,We can move `broadcast_bn_buffer` after ``` if...,"@@ -259,12 +259,12 @@ class DistEvalHook(EvalH...",class DistEvalHook(EvalHook):\n def after_t...,[{'filename': 'configs/_base_/schedules/schedu...,[]
35,265f6810-bf53-4fca-9b5a-130d7e7e9cc1,The patch changes the order of the blocks invo...,Correctness,gpt-4o-mini-2024-07-18,P000020,Medium,df_n3_3.csv,We can move `broadcast_bn_buffer` after ``` if...,"@@ -259,12 +259,12 @@ class DistEvalHook(EvalH...",class DistEvalHook(EvalHook):\n def after_t...,[{'filename': 'configs/_base_/schedules/schedu...,[]
36,6cf8a496-76e3-4296-99cb-c9fb5ae20901,Moving `_broadcast_bn_buffer()` below the `by_...,Correctness,gpt-5.4-mini-2026-03-17,P000020,Medium,df_n3_1.csv,We can move `broadcast_bn_buffer` after ``` if...,"@@ -259,12 +259,12 @@ class DistEvalHook(EvalH...",class DistEvalHook(EvalHook):\n def after_t...,[{'filename': 'configs/_base_/schedules/schedu...,[]
37,60d5f556-e3d9-4902-b914-69b48fd719e5,`prev_result()`/`next_result()` now call `resu...,Correctness,gpt-5.4-mini-2026-03-17,P000021,High,df_n3_1.csv,This signal should be on the `AbstractSearch` ...,"@@ -926,8 +926,6 @@ class AbstractTab(QWidget)...",class AbstractTab(QWidget):\n window_close_...,[{'filename': 'qutebrowser/browser/browsertab....,[{'filename': 'qutebrowser/browser/commands.py...
38,625aea66-aa42-4e34-a02f-129ae96315c7,Should the search_match_changed signal be remo...,Design,gpt-4o-mini-2024-07-18,P000021,Medium,df_n3_3.csv,This signal should be on the `AbstractSearch` ...,"@@ -926,8 +926,6 @@ class AbstractTab(QWidget)...",class AbstractTab(QWidget):\n window_close_...,[{'filename': 'qutebrowser/browser/browsertab....,[{'filename': 'qutebrowser/browser/commands.py...
39,e8f426cf-3cf2-4e7c-a16a-ee51e7a6c46e,`read_dropin_dir()` now unconditionally calls ...,Correctness,gpt-5.4-mini-2026-03-17,P000022,High,df_n3_1.csv,Please rename to `self.base.conf.read_dropin_d...,"@@ -840,7 +840,7 @@ class Cli(object):\n ...","class Cli(object):\n def configure(self, ar...","[{'filename': 'dnf/cli/cli.py', 'patch': ""@@ -...","[{'filename': 'dnf/conf/__init__.py', 'patch':..."
40,b0eff1f9-42ac-4d50-b3f5-13c02e532962,`read_dropin_dir()` iterates over every entry ...,Correctness,gpt-5.4-mini-2026-03-17,P000022,Medium,df_n3_1.csv,Please rename to `self.base.conf.read_dropin_d...,"@@ -840,7 +840,7 @@ class Cli(object):\n ...","class Cli(object):\n def configure(self, ar...","[{'filename': 'dnf/cli/cli.py', 'patch': ""@@ -...","[{'filename': 'dnf/conf/__init__.py', 'patch':..."
41,c3cd0e98-3d62-4461-9898-7176b4c37f6c,The method `read_dropin_dir()` appears to be c...,Correctness,gpt-4o-mini-2024-07-18,P000022,Medium,df_n3_3.csv,Please rename to `self.base.conf.read_dropin_d...,"@@ -840,7 +840,7 @@ class Cli(object):\n ...","class Cli(object):\n def configure(self, ar...","[{'filename': 'dnf/cli/cli.py', 'patch': ""@@ -...","[{'filename': 'dnf/conf/__init__.py', 'patch':..."
42,0ba75abf-59a5-4c65-9ff5-c2190495cff3,The line `source_address = self.server_conn.so...,Correctness,gpt-4o-mini-2024-07-18,P000023,High,df_n3_3.csv,Very minor nitpick: please use `source_address...,"@@ -157,7 +157,7 @@ class ServerConnectionMixi...",class ServerConnectionMixin(object):\n def ...,"[{'filename': 'libmproxy/protocol/base.py', 'p...",[{'filename': 'libmproxy/models/connections.py...
43,0a1bf0b9-7eab-4e99-8ba2-f0a10769bc3b,The new `formatted` string uses named placehol...,Correctness,gpt-5.4-mini-2026-03-17,P000024,High,df_n3_1.csv,Doesn't need all those parentheses. Change to ...,"@@ -167,7 +167,7 @@ class PokemonCatchWorker(B...",class PokemonCatchWorker(BaseTask):\n\n def...,[{'filename': 'pokemongo_bot/cell_workers/poke...,[]
44,c0b7c6c0-8469-4dd8-83e8-347f958a91c2,`c.fetchone()` is called after the `with self....,Correctness,gpt-5.4-mini-2026-03-17,P000024,Medium,df_n3_1.csv,Doesn't need all those parentheses. Change to ...,"@@ -167,7 +167,7 @@ class PokemonCatchWorker(B...",class PokemonCatchWorker(BaseTask):\n\n def...,[{'filename': 'pokemongo_bot/cell_workers/poke...,[]
45,c2b50e8b-600b-4057-bc31-78dae842a9ce,`caught_last_24_hour` now comes from `COUNT(en...,Correctness,gpt-5.4-mini-2026-03-17,P000024,Medium,df_n3_1.csv,Doesn't need all those parentheses. Change to ...,"@@ -167,7 +167,7 @@ class PokemonCatchWorker(B...",class PokemonCatchWorker(BaseTask):\n\n def...,[{'filename': 'pokemongo_bot/cell_workers/poke...,[]
46,a92c9171-d723-4888-82b2-4daea55b78ea,The formatted string in `emit_event` is missin...,Correctness,gpt-4o-mini-2024-07-18,P000024,High,df_n3_3.csv,Doesn't need all those parentheses. Change to ...,"@@ -167,7 +167,7 @@ class PokemonCatchWorker(B...",class PokemonCatchWorker(BaseTask):\n\n def...,[{'filename': 'pokemongo_bot/cell_workers/poke...,[]
47,b17c086b-b8ea-41fa-9f1d-94427d9a7760,The formatted message opens a parenthesized se...,Correctness,gpt-5.6-luna,P000024,Low,df_n3_2.csv,Doesn't need all those parentheses. Change to ...,"@@ -167,7 +167,7 @@ class PokemonCatchWorker(B...",class PokemonCatchWorker(BaseTask):\n\n def...,[{'filename': 'pokemongo_bot/cell_workers/poke...,[]
48,834f1e18-06fd-4fcf-8ff2-618bd99de998,The method name was changed from `next_occurre...,Correctness,gpt-4o-mini-2024-07-18,P000025,High,df_n3_3.csv,make sure this won't regress,"@@ -247,7 +247,7 @@ class test_crontab_remaini...",from celery.schedules import crontab\n\n\nclas...,[],[]
49,2de0461a-8ba0-4820-97a5-c65dd09e6d5d,`next_occurrance` is misspelled here. If any c...,Correctness,gpt-5.4-mini-2026-03-17,P000025,Medium,df_n3_1.csv,make sure this won't regress,"@@ -247,7 +247,7 @@ class test_crontab_remaini...",from celery.schedules import crontab\n\n\nclas...,[],[]