In [4]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [2]:
results=pd.read_csv('df_n4.csv')

In [14]:
import ast

def to_list(x):
    if isinstance(x, str):
        return ast.literal_eval(x)
    return x

results["num_comments"] = (
    results["comment_ids"]
    .apply(to_list)
    .apply(len)
)

In [18]:
results[5:].head(20)

,patch_id,num_comments,cluster_id,comment_ids,comments,generation_systems,categories,severities,synthesis_comment,agreement_scores,error
5,P000003,1,P000003_c0,['9fbca5f7-1892-4c12-82da-b8026b8801e9'],['The docstring for `iter_kubernetes_nodes` sa...,['gpt-4o-mini-2024-07-18'],['Documentation'],['Medium'],NaN,NaN,build_cluster_rows() missing 1 required positi...
6,P000004,1,P000004_c0,['37be13c2-958e-455f-a7e1-e9128b7f53c1'],['The docstring for `naive_dice_loss` does not...,['gpt-4o-mini-2024-07-18'],['Documentation'],['Medium'],NaN,[],NaN
7,P000004,1,P000004_c1,['78aa90a3-773f-4e6d-a437-4978cec0b3e8'],['The docstring still incorrectly calls the de...,['gpt-5.6-luna'],['Documentation'],['Low'],NaN,[],NaN
8,P000005,2,P000005_c0,"['e360ca3e-ae9c-4484-8f83-45f55e13de15', '5e37...",['If `PDBWriter.write()` still falls back to t...,"['gpt-5.4-mini-2026-03-17', 'gpt-4o-mini-2024-...","['Documentation', 'Documentation']","['Low', 'Medium']",Removing this warning leaves the deprecated se...,[1.0],NaN
9,P000006,2,P000006_c0,"['7abdc5b6-5608-4616-b616-17f2d7452def', '864b...",['Removing `self.compact_times()` from `KPISet...,"['gpt-5.4-mini-2026-03-17', 'gpt-4o-mini-2024-...","['Correctness', 'Correctness']","['Medium', 'High']",Removing response-time compaction from `recalc...,[1.0],NaN
10,P000007,2,P000007_c0,"['38c9032e-cb24-4cec-9a45-eafea75bf691', '4136...","[""By changing the assignment of `host` to `uti...","['gpt-4o-mini-2024-07-18', 'gpt-4o-mini-2024-0...","['Correctness', 'Maintainability']","['High', 'Medium']",Please verify that replacing the conditional b...,[1.0],NaN
11,P000007,1,P000007_c1,['59827895-0b28-44fa-8139-f477a0e3e26a'],['In the context of reusing functionality like...,['gpt-4o-mini-2024-07-18'],['Design'],['Medium'],NaN,[],NaN
12,P000007,1,P000007_c2,['87ee2b2c-6e0f-4cdf-a928-951f28086917'],['The comments preceding the code indicate the...,['gpt-4o-mini-2024-07-18'],['Documentation'],['Medium'],NaN,[],NaN
13,P000007,2,P000007_c3,"['5fbab32d-1cb9-4980-a82f-1ea8ac1747ff', '5a6c...",['Please call `to_native_string` from `._inter...,"['gpt-5.6-luna', 'gpt-5.4-mini-2026-03-17']","['Design', 'Correctness']","['Low', 'High']",Use the directly imported `to_native_string` f...,[1.0],NaN
14,P000008,2,P000008_c0,"['04d7279c-420f-48c5-baf5-05ddc9a94699', '963d...","['Could this continue using `getattr(cls, ""tas...","['gpt-5.6-luna', 'gpt-4o-mini-2024-07-18']","['Correctness', 'Correctness']","['Medium', 'High']",Accessing `cls.task_namespace` directly can ra...,[1.0],NaN
15,P000008,1,P000008_c1,['4ca1de55-b941-434f-9260-9ec3a133382d'],"['In `Register.__new__`, checking `cls.task_na...",['gpt-5.4-mini-2026-03-17'],['Correctness'],['High'],NaN,[],NaN
16,P000009,1,P000009_c0,['2b9c1eed-15da-407b-8348-40e5f064af53'],"[""The changed assertion for record['SY'] has i...",['gpt-4o-mini-2024-07-18'],['Correctness'],['Medium'],NaN,NaN,build_cluster_rows() missing 1 required positi...

In [ ]:
import pandas as pd
import ast

df = results.copy()

# Convert string representations of lists to Python lists
list_cols = [
    "comment_ids",
    "comments",
    "generation_systems",
    "categories",
    "severities",
]

for col in list_cols:
    df[col] = df[col].apply(
        lambda x: ast.literal_eval(x) if isinstance(x, str) else x
    )

# One row = one generated comment
exploded = df.explode(
    ["comment_ids",
     "comments",
     "generation_systems",
     "categories",
     "severities"],
    ignore_index=True
)

In [11]:
results.head(20)

,patch_id,num_comments,cluster_id,comment_ids,comments,generation_systems,categories,severities,synthesis_comment,agreement_scores,error
0,P000000,2,P000000_c0,"['19fcfc72-3118-4ada-968f-0f58419f01e3', '64da...","[""The docstring for the `head` method states i...","['gpt-4o-mini-2024-07-18', 'gpt-4o-mini-2024-0...","['Correctness', 'Documentation']","['Medium', 'Medium']",The health-check endpoint only returns an empt...,[1.0],NaN
1,P000001,2,P000001_c0,['361ae1e7-d815-4277-b258-37c8a2ec8c05'],['The change from `cross_entropy(logits[val_id...,['gpt-4o-mini-2024-07-18'],['Correctness'],['High'],NaN,[],NaN
2,P000001,2,P000001_c1,['1cfd802d-857b-4bcf-9188-6971310d95c0'],['Could this validation-only computation be wr...,['gpt-5.6-luna'],['Design'],['Low'],NaN,[],NaN
3,P000002,2,P000002_c0,['0344d8ec-1187-4ce1-8aae-7a9b7da07f24'],['Could we apply `fonts.debug_console` to `Con...,['gpt-5.4-mini-2026-03-17'],['Design'],['Low'],NaN,[],NaN
4,P000002,2,P000002_c1,['131aa221-e2f9-45bd-bc06-359b15f1de32'],['The `STYLESHEET` attribute in `ConsoleLineEd...,['gpt-4o-mini-2024-07-18'],['Correctness'],['Medium'],NaN,[],NaN
5,P000003,1,P000003_c0,['9fbca5f7-1892-4c12-82da-b8026b8801e9'],['The docstring for `iter_kubernetes_nodes` sa...,['gpt-4o-mini-2024-07-18'],['Documentation'],['Medium'],NaN,NaN,build_cluster_rows() missing 1 required positi...
6,P000004,2,P000004_c0,['37be13c2-958e-455f-a7e1-e9128b7f53c1'],['The docstring for `naive_dice_loss` does not...,['gpt-4o-mini-2024-07-18'],['Documentation'],['Medium'],NaN,[],NaN
7,P000004,2,P000004_c1,['78aa90a3-773f-4e6d-a437-4978cec0b3e8'],['The docstring still incorrectly calls the de...,['gpt-5.6-luna'],['Documentation'],['Low'],NaN,[],NaN
8,P000005,2,P000005_c0,"['e360ca3e-ae9c-4484-8f83-45f55e13de15', '5e37...",['If `PDBWriter.write()` still falls back to t...,"['gpt-5.4-mini-2026-03-17', 'gpt-4o-mini-2024-...","['Documentation', 'Documentation']","['Low', 'Medium']",Removing this warning leaves the deprecated se...,[1.0],NaN
9,P000006,2,P000006_c0,"['7abdc5b6-5608-4616-b616-17f2d7452def', '864b...",['Removing `self.compact_times()` from `KPISet...,"['gpt-5.4-mini-2026-03-17', 'gpt-4o-mini-2024-...","['Correctness', 'Correctness']","['Medium', 'High']",Removing response-time compaction from `recalc...,[1.0],NaN
10,P000007,6,P000007_c0,"['38c9032e-cb24-4cec-9a45-eafea75bf691', '4136...","[""By changing the assignment of `host` to `uti...","['gpt-4o-mini-2024-07-18', 'gpt-4o-mini-2024-0...","['Correctness', 'Maintainability']","['High', 'Medium']",Please verify that replacing the conditional b...,[1.0],NaN
11,P000007,6,P000007_c1,['59827895-0b28-44fa-8139-f477a0e3e26a'],['In the context of reusing functionality like...,['gpt-4o-mini-2024-07-18'],['Design'],['Medium'],NaN,[],NaN
12,P000007,6,P000007_c2,['87ee2b2c-6e0f-4cdf-a928-951f28086917'],['The comments preceding the code indicate the...,['gpt-4o-mini-2024-07-18'],['Documentation'],['Medium'],NaN,[],NaN
13,P000007,6,P000007_c3,"['5fbab32d-1cb9-4980-a82f-1ea8ac1747ff', '5a6c...",['Please call `to_native_string` from `._inter...,"['gpt-5.6-luna', 'gpt-5.4-mini-2026-03-17']","['Design', 'Correctness']","['Low', 'High']",Use the directly imported `to_native_string` f...,[1.0],NaN
14,P000008,3,P000008_c0,"['04d7279c-420f-48c5-baf5-05ddc9a94699', '963d...","['Could this continue using `getattr(cls, ""tas...","['gpt-5.6-luna', 'gpt-4o-mini-2024-07-18']","['Correctness', 'Correctness']","['Medium', 'High']",Accessing `cls.task_namespace` directly can ra...,[1.0],NaN
15,P000008,3,P000008_c1,['4ca1de55-b941-434f-9260-9ec3a133382d'],"['In `Register.__new__`, checking `cls.task_na...",['gpt-5.4-mini-2026-03-17'],['Correctness'],['High'],NaN,[],NaN
16,P000009,1,P000009_c0,['2b9c1eed-15da-407b-8348-40e5f064af53'],"[""The changed assertion for record['SY'] has i...",['gpt-4o-mini-2024-07-18'],['Correctness'],['Medium'],NaN,NaN,build_cluster_rows() missing 1 required positi...

In [4]:
severity_dist = (
    exploded
    .groupby(["generation_systems","severities"])
    .size()
    .unstack(fill_value=0)
)
severity_dist

severities               High  Low  Medium
generation_systems
gpt-4o-mini-2024-07-18      4    0      10
gpt-5.4-mini-2026-03-17     2    2       1
gpt-5.6-luna                0    3       1

In [5]:
# categories agreement 
agreement = (
    exploded
    .groupby("cluster_id")["categories"]
    .nunique()
)

agreement_rate = (agreement==1).mean()

print(f"Agreement = {agreement_rate:.2%}")

Agreement = 82.35%

In [6]:
# serevrity agreement 
agreement = (
    exploded
    .groupby("cluster_id")["severities"]
    .nunique()
)

agreement_rate = (agreement==1).mean()

print(f"Agreement = {agreement_rate:.2%}")

Agreement = 70.59%

In [7]:
cluster_sizes = (
    exploded
    .groupby("cluster_id")
    .size()
)

print(cluster_sizes.describe())

count    17.000000
mean      1.352941
std       0.492592
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       2.000000
dtype: float64

In [8]:
# Which categories produce the biggest consensus

tmp = exploded.copy()

tmp["cluster_size"] = (
    tmp.cluster_id.map(cluster_sizes)
)

tmp.groupby("categories")["cluster_size"].mean().sort_values(ascending=False)

categories
Maintainability    2.000000
Correctness        1.636364
Documentation      1.428571
Design             1.250000
Name: cluster_size, dtype: float64

In [9]:
from itertools import combinations
from collections import defaultdict

# Which systems agree the most
overlap = defaultdict(int)

clusters = exploded.groupby("cluster_id")

for _,g in clusters:

    systems = sorted(g.generation_systems.unique())

    for s1,s2 in combinations(systems,2):

        overlap[(s1,s2)] +=1

overlap

defaultdict(int,
            {('gpt-4o-mini-2024-07-18', 'gpt-5.4-mini-2026-03-17'): 2,
             ('gpt-5.4-mini-2026-03-17', 'gpt-5.6-luna'): 1,
             ('gpt-4o-mini-2024-07-18', 'gpt-5.6-luna'): 1})

In [ ]:
# Clusters found only by one system
unique_clusters = (
    exploded
    .groupby("cluster_id")
    .generation_systems
    .nunique()
)

single = unique_clusters[unique_clusters==1].index

exploded[
    exploded.cluster_id.isin(single)
].generation_systems.value_counts()

generation_systems
cohere/north-mini-code:free               13
tencent/hy3:free                           7
nvidia/nemotron-3-super-120b-a12b:free     5
poolside/laguna-m.1:free                   4
nvidia/nemotron-3-ultra-550b-a55b:free     4
Name: count, dtype: int64